// Mock dataset representing realistic enterprise fleet operations

export const INITIAL_VEHICLES = [
  {
    id: "VEH-101",
    name: "Tata Prima 5530.S #101",
    plate: "MH-04-EB-8472",
    type: "Heavy Semi-Truck",
    status: "in-transit", // 'in-transit' | 'idle' | 'maintenance' | 'out-of-service'
    driverId: "DRV-01",
    driverName: "Rajesh Sharma",
    fuelLevel: 78, // percentage
    batteryLevel: 94,
    odometer: 142850, // km
    speed: 68, // km/h
    healthScore: 92, // %
    engineTemp: 88, // °C
    payloadCapacity: 35000, // kg
    currentLoad: 24500, // kg
    lastServiceDate: "2026-08-15",
    nextServiceDue: "2026-11-15",
    location: {
      lat: 19.2812,
      lng: 73.0483,
      address: "NH-48 near Bhiwandi Freight Hub, Mumbai, MH",
      heading: 140
    },
    currentShipmentId: "SHP-8821"
  },
  {
    id: "VEH-102",
    name: "BharatBenz 3528R #102",
    plate: "GJ-01-AX-9319",
    type: "Heavy Multi-Axle Hauler",
    status: "in-transit",
    driverId: "DRV-02",
    driverName: "Vikram Patel",
    fuelLevel: 42,
    batteryLevel: 88,
    odometer: 98400,
    speed: 64,
    healthScore: 88,
    engineTemp: 92,
    payloadCapacity: 32000,
    currentLoad: 21800,
    lastServiceDate: "2026-07-20",
    nextServiceDue: "2026-10-25",
    location: {
      lat: 22.3072,
      lng: 73.1812,
      address: "NE-1 Expressway, Vadodara Bypass, Gujarat",
      heading: 25
    },
    currentShipmentId: "SHP-8822"
  },
  {
    id: "VEH-103",
    name: "Ashok Leyland 4220 HG #103",
    plate: "HR-26-DK-4491",
    type: "Semi-Trailer",
    status: "idle",
    driverId: "DRV-03",
    driverName: "Priya Nair",
    fuelLevel: 89,
    batteryLevel: 98,
    odometer: 64120,
    speed: 0,
    healthScore: 97,
    engineTemp: 45,
    payloadCapacity: 38000,
    currentLoad: 0,
    lastServiceDate: "2026-09-01",
    nextServiceDue: "2026-12-01",
    location: {
      lat: 28.3588,
      lng: 76.9405,
      address: "Manesar Industrial Freight Yard, Gurugram, HR",
      heading: 0
    },
    currentShipmentId: null
  },
  {
    id: "VEH-104",
    name: "Eicher Pro 6035 #104",
    plate: "KA-01-MJ-8823",
    type: "Refrigerated Carrier",
    status: "in-transit",
    driverId: "DRV-04",
    driverName: "Amit Verma",
    fuelLevel: 24, // low fuel trigger
    batteryLevel: 72,
    odometer: 178300,
    speed: 55,
    healthScore: 79,
    engineTemp: 102, // high engine temp trigger
    payloadCapacity: 28000,
    currentLoad: 22400,
    lastServiceDate: "2026-06-11",
    nextServiceDue: "2026-10-10",
    location: {
      lat: 12.8452,
      lng: 77.6602,
      address: "NH-44 Hosur-Electronic City Corridor, Bengaluru, KA",
      heading: 110
    },
    currentShipmentId: "SHP-8824"
  },
  {
    id: "VEH-105",
    name: "Tata Ultra T.7 EV #105",
    plate: "DL-01-EV-5021",
    type: "Electric Urban Delivery Van",
    status: "in-transit",
    driverId: "DRV-05",
    driverName: "Suresh Kumar",
    fuelLevel: 65, // electric battery charge %
    batteryLevel: 65,
    odometer: 28900,
    speed: 38,
    healthScore: 99,
    engineTemp: 52,
    payloadCapacity: 4500,
    currentLoad: 3200,
    lastServiceDate: "2026-08-28",
    nextServiceDue: "2026-11-28",
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: "Connaught Place Last-Mile Hub, New Delhi, DL",
      heading: 45
    },
    currentShipmentId: "SHP-8825"
  },
  {
    id: "VEH-106",
    name: "Mahindra Blazo X 49 #106",
    plate: "PB-10-CZ-6192",
    type: "Heavy Semi-Truck",
    status: "maintenance",
    driverId: "DRV-17",
    driverName: "Gurpreet Dhillon",
    fuelLevel: 51,
    batteryLevel: 82,
    odometer: 210450,
    speed: 0,
    healthScore: 64,
    engineTemp: 35,
    payloadCapacity: 35000,
    currentLoad: 0,
    lastServiceDate: "2026-05-10",
    nextServiceDue: "2026-10-01",
    location: {
      lat: 30.9010,
      lng: 75.8573,
      address: "Sahnewal Dry Port Depot Bay 4, Ludhiana, PB",
      heading: 0
    },
    currentShipmentId: null
  },
  {
    id: "VEH-107",
    name: "BharatBenz 1617R #107",
    plate: "TN-09-CB-3392",
    type: "Medium Delivery Truck",
    status: "in-transit",
    driverId: "DRV-06",
    driverName: "Arjun Reddy",
    fuelLevel: 82,
    batteryLevel: 95,
    odometer: 43200,
    speed: 62,
    healthScore: 94,
    engineTemp: 84,
    payloadCapacity: 9500,
    currentLoad: 7200,
    lastServiceDate: "2026-08-01",
    nextServiceDue: "2026-11-01",
    location: {
      lat: 12.9815,
      lng: 79.9723,
      address: "Sriperumbudur Auto-Pharma Cluster, Chennai, TN",
      heading: 320
    },
    currentShipmentId: "SHP-8827"
  },
  {
    id: "VEH-108",
    name: "Tata Signa 4825.TK #108",
    plate: "WB-02-AK-1904",
    type: "Multi-Axle Cargo Carrier",
    status: "idle",
    driverId: "DRV-08",
    driverName: "Manoj Singh",
    fuelLevel: 93,
    batteryLevel: 96,
    odometer: 77800,
    speed: 0,
    healthScore: 95,
    engineTemp: 40,
    payloadCapacity: 38000,
    currentLoad: 0,
    lastServiceDate: "2026-07-30",
    nextServiceDue: "2026-10-30",
    location: {
      lat: 22.6823,
      lng: 88.2934,
      address: "Dankuni Inland Container Depot, Kolkata, WB",
      heading: 0
    },
    currentShipmentId: null
  }
];

export const INITIAL_DRIVERS = [
  {
    id: "DRV-01",
    name: "Rajesh Sharma",
    email: "rajesh.sharma@bharatlogix.in",
    phone: "+91 98201 44582",
    avatar: "/assets/drivers/drv-01.jpg",
    status: "on-route",
    licenseNumber: "DL-MH-02-2016-84729",
    licenseType: "Commercial Class A",
    licenseExpiry: "2029-04-14",
    experienceYears: 11,
    assignedVehicleId: "VEH-101",
    assignedVehicleName: "Tata Prima 5530.S #101",
    hub: "Bhiwandi Gateway Hub, Mumbai",
    state: "Maharashtra",
    safetyScore: 98,
    onTimeDeliveryRate: 98.4,
    totalDeliveries: 542,
    milesLogged: 248900,
    rating: 4.9,
    specialty: "Heavy Haul Interstate Captain",
    badge: "Top Safety Captain 🏆",
    joinDate: "2020-03-12"
  },
  {
    id: "DRV-02",
    name: "Vikram Patel",
    email: "vikram.patel@bharatlogix.in",
    phone: "+91 98791 22310",
    avatar: "/assets/drivers/drv-02.jpg",
    status: "on-route",
    licenseNumber: "DL-GJ-01-2018-93214",
    licenseType: "Commercial Class A - HazMat",
    licenseExpiry: "2028-11-20",
    experienceYears: 8,
    assignedVehicleId: "VEH-102",
    assignedVehicleName: "BharatBenz 2823R #102",
    hub: "Sanand Industrial Depot, Ahmedabad",
    state: "Gujarat",
    safetyScore: 96,
    onTimeDeliveryRate: 97.2,
    totalDeliveries: 418,
    milesLogged: 195400,
    rating: 4.8,
    specialty: "HazMat & Chemicals",
    badge: "HazMat Specialist 🛡️",
    joinDate: "2021-07-15"
  },
  {
    id: "DRV-03",
    name: "Priya Nair",
    email: "priya.nair@bharatlogix.in",
    phone: "+91 94471 83290",
    avatar: "/assets/drivers/drv-03.jpg",
    status: "available",
    licenseNumber: "DL-KL-07-2017-49201",
    licenseType: "Commercial Class A",
    licenseExpiry: "2029-01-30",
    experienceYears: 9,
    assignedVehicleId: "VEH-103",
    assignedVehicleName: "Ashok Leyland 4220 #103",
    hub: "Vallarpadam Port Logistics, Kochi",
    state: "Kerala",
    safetyScore: 99,
    onTimeDeliveryRate: 99.5,
    totalDeliveries: 615,
    milesLogged: 312000,
    rating: 5.0,
    specialty: "Intermodal Container Freight",
    badge: "Zero-Incident Champion ⭐",
    joinDate: "2019-01-10"
  },
  {
    id: "DRV-04",
    name: "Amit Verma",
    email: "amit.verma@bharatlogix.in",
    phone: "+91 98110 54921",
    avatar: "/assets/drivers/drv-04.jpg",
    status: "on-route",
    licenseNumber: "DL-DL-04-2019-21849",
    licenseType: "Commercial Class A - Tanker",
    licenseExpiry: "2027-12-18",
    experienceYears: 7,
    assignedVehicleId: "VEH-104",
    assignedVehicleName: "Mahindra Blazo X 49 #104",
    hub: "Gurugram Expressway Logistics, NCR",
    state: "Delhi NCR",
    safetyScore: 93,
    onTimeDeliveryRate: 94.6,
    totalDeliveries: 340,
    milesLogged: 164000,
    rating: 4.7,
    specialty: "Refrigerated Cold-Chain",
    badge: "Cold-Chain Specialist ❄️",
    joinDate: "2022-04-05"
  },
  {
    id: "DRV-05",
    name: "Suresh Kumar",
    email: "suresh.kumar@bharatlogix.in",
    phone: "+91 98450 71203",
    avatar: "/assets/drivers/drv-05.jpg",
    status: "on-route",
    licenseNumber: "DL-KA-01-2020-65012",
    licenseType: "Commercial Class B - EV Specialized",
    licenseExpiry: "2028-09-09",
    experienceYears: 6,
    assignedVehicleId: "VEH-105",
    assignedVehicleName: "Eicher Pro 6028 #105",
    hub: "Electronic City Tech Depot, Bengaluru",
    state: "Karnataka",
    safetyScore: 97,
    onTimeDeliveryRate: 98.8,
    totalDeliveries: 560,
    milesLogged: 89400,
    rating: 4.9,
    specialty: "Last-Mile Green Logistics",
    badge: "Eco-Fleet Pioneer ⚡",
    joinDate: "2021-01-20"
  },
  {
    id: "DRV-06",
    name: "Arjun Reddy",
    email: "arjun.reddy@bharatlogix.in",
    phone: "+91 98490 63821",
    avatar: "/assets/drivers/drv-06.jpg",
    status: "on-route",
    licenseNumber: "DL-TS-09-2018-88310",
    licenseType: "Commercial Class B",
    licenseExpiry: "2028-06-14",
    experienceYears: 8,
    assignedVehicleId: "VEH-106",
    assignedVehicleName: "Tata Ultra T.7 EV #106",
    hub: "Shamshabad Air Freight Center, Hyderabad",
    state: "Telangana",
    safetyScore: 95,
    onTimeDeliveryRate: 96.2,
    totalDeliveries: 420,
    milesLogged: 147500,
    rating: 4.8,
    specialty: "Pharma Courier Logistics",
    badge: "Express Courier Master 🚀",
    joinDate: "2021-09-18"
  },
  {
    id: "DRV-07",
    name: "Sunita Rao",
    email: "sunita.rao@bharatlogix.in",
    phone: "+91 98220 39184",
    avatar: "/assets/drivers/drv-07.jpg",
    status: "off-duty",
    licenseNumber: "DL-MH-12-2014-41920",
    licenseType: "Commercial Class A",
    licenseExpiry: "2029-02-28",
    experienceYears: 14,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "Chakan Industrial Corridor, Pune",
    state: "Maharashtra",
    safetyScore: 98,
    onTimeDeliveryRate: 99.0,
    totalDeliveries: 820,
    milesLogged: 412000,
    rating: 4.9,
    specialty: "Automotive Freight Senior Lead",
    badge: "Master Fleet Veteran 🎖️",
    joinDate: "2018-05-11"
  },
  {
    id: "DRV-08",
    name: "Manoj Singh",
    email: "manoj.singh@bharatlogix.in",
    phone: "+91 94150 82910",
    avatar: "/assets/drivers/drv-08.jpg",
    status: "available",
    licenseNumber: "DL-UP-32-2015-11029",
    licenseType: "Commercial Class A",
    licenseExpiry: "2027-10-15",
    experienceYears: 12,
    assignedVehicleId: "VEH-108",
    assignedVehicleName: "Ashok Leyland BOSS #108",
    hub: "Transport Nagar Hub, Lucknow",
    state: "Uttar Pradesh",
    safetyScore: 96,
    onTimeDeliveryRate: 95.8,
    totalDeliveries: 670,
    milesLogged: 335000,
    rating: 4.8,
    specialty: "Interstate Cross-Docking",
    badge: "Long-Haul Specialist 🚛",
    joinDate: "2019-06-22"
  },
  {
    id: "DRV-09",
    name: "Deepak Joshi",
    email: "deepak.joshi@bharatlogix.in",
    phone: "+91 94140 66281",
    avatar: "/assets/drivers/drv-09.jpg",
    status: "on-route",
    licenseNumber: "DL-RJ-14-2019-55019",
    licenseType: "Commercial Class A",
    licenseExpiry: "2028-08-30",
    experienceYears: 7,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "VKI Logistics Corridor, Jaipur",
    state: "Rajasthan",
    safetyScore: 94,
    onTimeDeliveryRate: 96.0,
    totalDeliveries: 310,
    milesLogged: 142000,
    rating: 4.7,
    specialty: "Dry Van Interstate Routing",
    badge: "Highway Cruiser 🛣️",
    joinDate: "2022-08-14"
  },
  {
    id: "DRV-10",
    name: "Ananya Deshmukh",
    email: "ananya.d@bharatlogix.in",
    phone: "+91 98230 44912",
    avatar: "/assets/drivers/drv-10.jpg",
    status: "available",
    licenseNumber: "DL-MH-31-2020-77192",
    licenseType: "Commercial Class B - EV Specialized",
    licenseExpiry: "2029-05-19",
    experienceYears: 5,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "MIHAN Cargo SEZ, Nagpur",
    state: "Maharashtra",
    safetyScore: 99,
    onTimeDeliveryRate: 99.1,
    totalDeliveries: 280,
    milesLogged: 95000,
    rating: 4.9,
    specialty: "Time-Definite Delivery",
    badge: "High Accuracy Operator 🎯",
    joinDate: "2022-11-04"
  },
  {
    id: "DRV-11",
    name: "Rohan Mehra",
    email: "rohan.mehra@bharatlogix.in",
    phone: "+91 94250 88123",
    avatar: "/assets/drivers/drv-12.jpg",
    status: "on-route",
    licenseNumber: "DL-MP-09-2018-34821",
    licenseType: "Commercial Class A",
    licenseExpiry: "2028-07-12",
    experienceYears: 8,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "Pithampur Multimodal Logistics Park, Indore",
    state: "Madhya Pradesh",
    safetyScore: 95,
    onTimeDeliveryRate: 96.5,
    totalDeliveries: 395,
    milesLogged: 182000,
    rating: 4.8,
    specialty: "Cross-Corridor Dispatch",
    badge: "Cross-Country Pro 🗺️",
    joinDate: "2021-05-18"
  },
  {
    id: "DRV-12",
    name: "Pooja Gupta",
    email: "pooja.gupta@bharatlogix.in",
    phone: "+91 98300 29104",
    avatar: "/assets/drivers/drv-13.jpg",
    status: "on-break",
    licenseNumber: "DL-WB-02-2019-66120",
    licenseType: "Commercial Class B",
    licenseExpiry: "2027-09-15",
    experienceYears: 6,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "Dankuni Cargo Port, Kolkata",
    state: "West Bengal",
    safetyScore: 98,
    onTimeDeliveryRate: 98.2,
    totalDeliveries: 310,
    milesLogged: 118000,
    rating: 4.9,
    specialty: "High-Value Cargo Handling",
    badge: "Precision Logistics ⏱️",
    joinDate: "2022-02-14"
  },
  {
    id: "DRV-17",
    name: "Gurpreet Dhillon",
    email: "gurpreet.dhillon@bharatlogix.in",
    phone: "+91 98150 99281",
    avatar: "/assets/drivers/drv-11.jpg",
    status: "on-route",
    licenseNumber: "DL-PB-10-2012-73921",
    licenseType: "Commercial Class A",
    licenseExpiry: "2029-08-22",
    experienceYears: 14,
    assignedVehicleId: "VEH-106",
    assignedVehicleName: "Tata Ultra T.7 EV #106",
    hub: "Sahnewal Dry Port Freight Hub, Ludhiana",
    state: "Punjab",
    safetyScore: 99,
    onTimeDeliveryRate: 98.7,
    totalDeliveries: 810,
    milesLogged: 460000,
    rating: 5.0,
    specialty: "Heavy Industrial Goods",
    badge: "Elite Fleet Master 🏆",
    joinDate: "2017-06-19"
  },
  {
    id: "DRV-20",
    name: "Divya Pillai",
    email: "divya.pillai@bharatlogix.in",
    phone: "+91 94470 66129",
    avatar: "/assets/drivers/drv-14.jpg",
    status: "available",
    licenseNumber: "DL-KL-01-2020-99210",
    licenseType: "Commercial Class B - EV Specialized",
    licenseExpiry: "2029-11-15",
    experienceYears: 5,
    assignedVehicleId: null,
    assignedVehicleName: "None",
    hub: "Vizhinjam Transshipment Hub, Thiruvananthapuram",
    state: "Kerala",
    safetyScore: 98,
    onTimeDeliveryRate: 99.2,
    totalDeliveries: 290,
    milesLogged: 92000,
    rating: 4.9,
    specialty: "High-Speed EV Distribution",
    badge: "Coastal Route Pro 🌊",
    joinDate: "2023-01-15"
  }
];

export const INITIAL_SHIPMENTS = [
  {
    id: "SHP-8821",
    customer: "Reliance Retail Logistics",
    cargoType: "Fast-Moving Consumer Electronics",
    priority: "urgent", // 'urgent' | 'high' | 'normal'
    weightKg: 8400,
    origin: {
      city: "Mumbai, MH",
      address: "Bhiwandi Gateway Hub, Bldg 4",
      lat: 19.2812,
      lng: 73.0483
    },
    destination: {
      city: "Bengaluru, KA",
      address: "Electronic City Logistics Park",
      lat: 12.8452,
      lng: 77.6602
    },
    assignedVehicleId: "VEH-101",
    assignedVehiclePlate: "MH-04-EB-8472",
    assignedDriverId: "DRV-01",
    assignedDriverName: "Rajesh Sharma",
    status: "in-transit", // 'pending' | 'dispatched' | 'in-transit' | 'out-for-delivery' | 'delivered' | 'delayed'
    eta: "Today, 18:30",
    departureTime: "2026-10-06T06:00:00",
    currentProgressPercent: 68,
    estimatedDistanceKm: 980,
    distanceRemainingKm: 310,
    events: [
      { timestamp: "2026-10-06 06:00", title: "Dispatched from Bhiwandi Hub", status: "completed" },
      { timestamp: "2026-10-06 08:30", title: "Pune Expressway Tollway Cleared", status: "completed" },
      { timestamp: "2026-10-06 11:45", title: "Passing Belagavi Corridor Checkpoint", status: "completed" },
      { timestamp: "2026-10-06 18:30", title: "Estimated Delivery Bengaluru Hub", status: "pending" }
    ]
  },
  {
    id: "SHP-8822",
    customer: "Tata Motors Commercial Parts",
    cargoType: "Engine Assemblies & Transmission Units",
    priority: "high",
    weightKg: 12500,
    origin: {
      city: "Gurugram, HR",
      address: "Manesar Freight Terminal D",
      lat: 28.3588,
      lng: 76.9405
    },
    destination: {
      city: "Ahmedabad, GJ",
      address: "Sanand Auto Logistics Cluster",
      lat: 23.0225,
      lng: 72.5714
    },
    assignedVehicleId: "VEH-102",
    assignedVehiclePlate: "GJ-01-AX-9319",
    assignedDriverId: "DRV-02",
    assignedDriverName: "Vikram Patel",
    status: "in-transit",
    eta: "Tomorrow, 09:15",
    departureTime: "2026-10-06T08:15:00",
    currentProgressPercent: 42,
    estimatedDistanceKm: 890,
    distanceRemainingKm: 516,
    events: [
      { timestamp: "2026-10-06 08:15", title: "Loaded & Inspected at Manesar Hub", status: "completed" },
      { timestamp: "2026-10-06 10:45", title: "En Route NE-1 Vadodara Expressway", status: "completed" },
      { timestamp: "2026-10-07 09:15", title: "Delivery to Sanand Plant", status: "pending" }
    ]
  },
  {
    id: "SHP-8824",
    customer: "Fresho & BigBasket Supply",
    cargoType: "Cold-Chain Dairy & Organic Produce",
    priority: "urgent",
    weightKg: 14200,
    origin: {
      city: "Bengaluru, KA",
      address: "Hosur Industrial Logistics Center",
      lat: 12.8452,
      lng: 77.6602
    },
    destination: {
      city: "Chennai, TN",
      address: "Sriperumbudur Cold Distribution Hub",
      lat: 12.9815,
      lng: 79.9723
    },
    assignedVehicleId: "VEH-104",
    assignedVehiclePlate: "KA-01-MJ-8823",
    assignedDriverId: "DRV-04",
    assignedDriverName: "Amit Verma",
    status: "delayed", // delayed due to high engine temp / traffic
    eta: "Today, 21:45 (Delayed by 2h)",
    departureTime: "2026-10-06T07:00:00",
    currentProgressPercent: 55,
    estimatedDistanceKm: 340,
    distanceRemainingKm: 153,
    delayReason: "High engine temperature alert triggered mandatory cooling stop near Ranipet on NH-48",
    events: [
      { timestamp: "2026-10-06 07:00", title: "Dispatched Hosur Freight Hub", status: "completed" },
      { timestamp: "2026-10-06 09:40", title: "Vellore Bypass Checkpoint Cleared", status: "completed" },
      { timestamp: "2026-10-06 11:10", title: "Engine Coolant Alert - Safety Pullover Ranipet", status: "alert" },
      { timestamp: "2026-10-06 21:45", title: "Revised Delivery Sriperumbudur Hub", status: "pending" }
    ]
  },
  {
    id: "SHP-8825",
    customer: "Amazon Prime Logistics India",
    cargoType: "Omnichannel Consumer Electronics",
    priority: "high",
    weightKg: 2100,
    origin: {
      city: "Gurugram, HR",
      address: "Udyog Vihar Fulfillment Center",
      lat: 28.5000,
      lng: 77.0800
    },
    destination: {
      city: "New Delhi, DL",
      address: "Connaught Place & Okhla Terminal",
      lat: 28.6139,
      lng: 77.2090
    },
    assignedVehicleId: "VEH-105",
    assignedVehiclePlate: "DL-01-EV-5021",
    assignedDriverId: "DRV-05",
    assignedDriverName: "Suresh Kumar",
    status: "in-transit",
    eta: "Today, 14:00",
    departureTime: "2026-10-06T09:30:00",
    currentProgressPercent: 75,
    estimatedDistanceKm: 42,
    distanceRemainingKm: 10,
    events: [
      { timestamp: "2026-10-06 09:30", title: "Departure Udyog Vihar Logistics", status: "completed" },
      { timestamp: "2026-10-06 10:15", title: "DND Flyway Corridor Cleared", status: "completed" },
      { timestamp: "2026-10-06 14:00", title: "Central Delhi Hub Dropoff", status: "pending" }
    ]
  },
  {
    id: "SHP-8827",
    customer: "Adani Solar & Clean Energy",
    cargoType: "Photovoltaic Inverters & Solar Modules",
    priority: "normal",
    weightKg: 3400,
    origin: {
      city: "Chennai, TN",
      address: "Ennore Port Container Freight Station",
      lat: 13.2500,
      lng: 80.3200
    },
    destination: {
      city: "Hyderabad, TS",
      address: "Genome Valley Clean Tech Depot",
      lat: 17.5800,
      lng: 78.6000
    },
    assignedVehicleId: "VEH-107",
    assignedVehiclePlate: "TN-09-CB-3392",
    assignedDriverId: "DRV-06",
    assignedDriverName: "Arjun Reddy",
    status: "in-transit",
    eta: "Today, 17:10",
    departureTime: "2026-10-06T10:00:00",
    currentProgressPercent: 35,
    estimatedDistanceKm: 625,
    distanceRemainingKm: 406,
    events: [
      { timestamp: "2026-10-06 10:00", title: "Picked up at Ennore Port", status: "completed" },
      { timestamp: "2026-10-06 11:30", title: "Nellore Tollway Passed", status: "completed" },
      { timestamp: "2026-10-06 17:10", title: "Target Delivery Hyderabad", status: "pending" }
    ]
  },
  {
    id: "SHP-8819",
    customer: "Bharat Forge Industrial Ltd",
    cargoType: "Precision Machined Auto Components",
    priority: "normal",
    weightKg: 28400,
    origin: {
      city: "Pune, MH",
      address: "Chakan Auto Cluster Freight Yard",
      lat: 18.7606,
      lng: 73.8636
    },
    destination: {
      city: "Mumbai, MH",
      address: "JNPT Port Container Terminal 3",
      lat: 18.9500,
      lng: 72.9500
    },
    assignedVehicleId: "VEH-103",
    assignedVehiclePlate: "HR-26-DK-4491",
    assignedDriverId: "DRV-03",
    assignedDriverName: "Priya Nair",
    status: "delivered",
    eta: "Completed 2026-10-05 16:45",
    departureTime: "2026-10-05T08:00:00",
    currentProgressPercent: 100,
    estimatedDistanceKm: 145,
    distanceRemainingKm: 0,
    events: [
      { timestamp: "2026-10-05 08:00", title: "Departed Chakan Facility", status: "completed" },
      { timestamp: "2026-10-05 12:30", title: "Khalapur Tollway Checkpoint", status: "completed" },
      { timestamp: "2026-10-05 16:45", title: "Delivered & Signed at JNPT Port", status: "completed" }
    ]
  },
  {
    id: "SHP-8815",
    customer: "Haldia Petrochemicals Corp",
    cargoType: "Specialized Polymer Pellets",
    priority: "urgent",
    weightKg: 16000,
    origin: {
      city: "Kolkata, WB",
      address: "Dankuni Inland Container Depot",
      lat: 22.6823,
      lng: 88.2934
    },
    destination: {
      city: "Patna, BR",
      address: "Fatuha Logistics Hub Terminal 2",
      lat: 25.5000,
      lng: 85.3100
    },
    assignedVehicleId: "VEH-108",
    assignedVehiclePlate: "WB-02-AK-1904",
    assignedDriverId: "DRV-08",
    assignedDriverName: "Manoj Singh",
    status: "delivered",
    eta: "Completed 2026-10-04 18:00",
    departureTime: "2026-10-04T07:30:00",
    currentProgressPercent: 100,
    estimatedDistanceKm: 585,
    distanceRemainingKm: 0,
    events: [
      { timestamp: "2026-10-04 07:30", title: "Departed Dankuni Inland Depot", status: "completed" },
      { timestamp: "2026-10-04 13:00", title: "Asansol Border Crossing", status: "completed" },
      { timestamp: "2026-10-04 18:00", title: "Consignee Signature Verified - Delivered", status: "completed" }
    ]
  },
  {
    id: "SHP-8828",
    customer: "Dr. Reddy's Laboratories",
    cargoType: "Active Pharmaceutical Ingredients (API)",
    priority: "high",
    weightKg: 5200,
    origin: {
      city: "Hyderabad, TS",
      address: "Bachupally Bio-Pharma Logistics Center",
      lat: 17.5400,
      lng: 78.3600
    },
    destination: {
      city: "Bengaluru, KA",
      address: "Whitefield Biotech Distribution Dock",
      lat: 12.9698,
      lng: 77.7500
    },
    assignedVehicleId: null,
    assignedVehiclePlate: "Unassigned",
    assignedDriverId: null,
    assignedDriverName: "Unassigned",
    status: "pending",
    eta: "Pending Driver Assignment",
    departureTime: null,
    currentProgressPercent: 0,
    estimatedDistanceKm: 570,
    distanceRemainingKm: 570,
    events: [
      { timestamp: "2026-10-06 09:00", title: "Order Created in System", status: "completed" },
      { timestamp: "--:--", title: "Awaiting Vehicle & Driver Dispatch", status: "pending" }
    ]
  }
];

export const INITIAL_ALERTS = [
  {
    id: "ALT-901",
    type: "delayed-shipment",
    severity: "critical", // 'critical' | 'warning' | 'info'
    title: "Shipment Delay Critical: SHP-8824",
    message: "Refrigerated Carrier #104 reported engine temp of 102°C. Vehicle halted for cooldown near Ranipet on NH-48. ETA delayed by 2h.",
    timestamp: "8 mins ago",
    read: false,
    relatedEntityId: "SHP-8824",
    category: "Shipment"
  },
  {
    id: "ALT-902",
    type: "maintenance",
    severity: "warning",
    title: "Low Fuel Advisory: Eicher Pro #104",
    message: "Vehicle VEH-104 diesel reserve dropped to 22%. Recommended refuel stop at IndianOil COCO Station NH-48 within 18 km.",
    timestamp: "20 mins ago",
    read: false,
    relatedEntityId: "VEH-104",
    category: "Vehicle"
  },
  {
    id: "ALT-903",
    type: "maintenance",
    severity: "warning",
    title: "Scheduled Service Overdue: Mahindra Blazo #106",
    message: "Asset VEH-106 is due for 200,000 km hub-greasing & brake liner inspection. Scheduled service overdue by 5 days at Ludhiana Depot.",
    timestamp: "45 mins ago",
    read: false,
    relatedEntityId: "VEH-106",
    category: "Vehicle"
  },
  {
    id: "ALT-904",
    type: "geofence",
    severity: "critical",
    title: "Geofence Corridor Deviation: SHP-8822",
    message: "Asset VEH-102 drifted 4.8 km outside authorized NH-48 freight corridor near Jaipur bypass. Dispatcher acknowledgment requested.",
    timestamp: "1 hour ago",
    read: false,
    relatedEntityId: "SHP-8822",
    category: "Shipment"
  },
  {
    id: "ALT-905",
    type: "driver-status",
    severity: "warning",
    title: "Driver Duty Limit Warning: Vikram Patel",
    message: "Captain Vikram Patel has logged 8.5 continuous driving hours. Mandatory 45-minute fatigue rest break required within 30 mins.",
    timestamp: "2 hours ago",
    read: false,
    relatedEntityId: "DRV-02",
    category: "Driver"
  },
  {
    id: "ALT-906",
    type: "delivery-update",
    severity: "info",
    title: "Express Milestone Checkpoint: SHP-8821",
    message: "Captain Rajesh Sharma cleared Belagavi Corridor Checkpoint on route to Bengaluru. Verified on track for 18:30 on-time delivery SLA.",
    timestamp: "3 hours ago",
    read: false,
    relatedEntityId: "SHP-8821",
    category: "Delivery"
  }
];

export const FLEET_METRICS = {
  onTimeDeliveryRate: 96.4,
  fleetUtilizationRate: 87.5,
  fuelEfficiencyKmpl: 4.8,
  totalDistanceThisWeek: 68400,
  carbonEmissionsSavedKg: 5240,
  averageDowntimeHours: 2.8
};
